services:
  komari:
    image: zaofengyue/komari:latest
    container_name: komari
    restart: unless-stopped
    ports:
      - "25774:25774"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
      - PORT=25774
